# Generated by Django 5.2.6 on 2025-09-27 14:22

import django.core.files.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regex_processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemetadata",
            name="parsed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Parse time"
            ),
        ),
        migrations.AlterField(
            model_name="fileprocessingrequest",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="fileprocessingrequest",
            name="natural_language_description",
            field=models.TextField(
                help_text="User-described requirements, e.g.: Format all phone numbers as xxx-xxxx-xxxx",
                verbose_name="Natural language description",
            ),
        ),
        migrations.AlterField(
            model_name="fileprocessingrequest",
            name="processed_file",
            field=models.FileField(
                blank=True,
                help_text="File after processing completion",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="media/processed_files/"
                ),
                upload_to="processed_files/",
                verbose_name="Processed result file",
            ),
        ),
        migrations.AlterField(
            model_name="fileprocessingrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="generatedregex",
            name="confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="LLM-generated confidence score (0-1)",
                null=True,
                verbose_name="Confidence score",
            ),
        ),
        migrations.AlterField(
            model_name="generatedregex",
            name="flags",
            field=models.JSONField(
                default=dict,
                help_text="Regex flags such as ignorecase, etc.",
                verbose_name="Regex flags",
            ),
        ),
        migrations.AlterField(
            model_name="generatedregex",
            name="generated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Generation time"
            ),
        ),
        migrations.AlterField(
            model_name="generatedregex",
            name="pattern",
            field=models.TextField(
                help_text="LLM-generated regular expression",
                verbose_name="Regex pattern",
            ),
        ),
        migrations.AlterField(
            model_name="processinglog",
            name="details",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Details"
            ),
        ),
    ]
